# Generated by Django 6.0.1 on 2026-01-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('car', 'Car Care'), ('home', 'Home Cleaning'), ('commercial', 'Office & Shop Cleaning'), ('move', 'Move In / Move Out'), ('upholstery', 'Upholstery & Fabrics')], max_length=20)),
                ('short_description', models.CharField(max_length=255)),
                ('full_description', models.TextField(blank=True)),
                ('starting_price', models.DecimalField(decimal_places=2, help_text='Starting price in GBP', max_digits=8)),
                ('ideal_for', models.CharField(help_text='e.g., Vehicle / Home / Business', max_length=100)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
